// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: puzzles/v1/puzzles.proto

package puzzlesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPuzzleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleRequest) Reset() {
	*x = GetPuzzleRequest{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleRequest) ProtoMessage() {}

func (x *GetPuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleRequest.ProtoReflect.Descriptor instead.
func (*GetPuzzleRequest) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{0}
}

func (x *GetPuzzleRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type GetPuzzleResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Id            string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameState     []*GetPuzzleResponse_PositionSchema `protobuf:"bytes,2,rep,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	PlayerSide    string                              `protobuf:"bytes,3,opt,name=player_side,json=playerSide,proto3" json:"player_side,omitempty"`
	Moves         []string                            `protobuf:"bytes,4,rep,name=moves,proto3" json:"moves,omitempty"`
	Level         int32                               `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleResponse) Reset() {
	*x = GetPuzzleResponse{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleResponse) ProtoMessage() {}

func (x *GetPuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleResponse.ProtoReflect.Descriptor instead.
func (*GetPuzzleResponse) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{1}
}

func (x *GetPuzzleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPuzzleResponse) GetGameState() []*GetPuzzleResponse_PositionSchema {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetPuzzleResponse) GetPlayerSide() string {
	if x != nil {
		return x.PlayerSide
	}
	return ""
}

func (x *GetPuzzleResponse) GetMoves() []string {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *GetPuzzleResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetPuzzleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleByIdRequest) Reset() {
	*x = GetPuzzleByIdRequest{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleByIdRequest) ProtoMessage() {}

func (x *GetPuzzleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPuzzleByIdRequest) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{2}
}

func (x *GetPuzzleByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPuzzleByIdResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Id            string                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameState     []*GetPuzzleByIdResponse_PositionSchema `protobuf:"bytes,2,rep,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	PlayerSide    string                                  `protobuf:"bytes,3,opt,name=player_side,json=playerSide,proto3" json:"player_side,omitempty"`
	Moves         []string                                `protobuf:"bytes,4,rep,name=moves,proto3" json:"moves,omitempty"`
	Level         int32                                   `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleByIdResponse) Reset() {
	*x = GetPuzzleByIdResponse{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleByIdResponse) ProtoMessage() {}

func (x *GetPuzzleByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPuzzleByIdResponse) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{3}
}

func (x *GetPuzzleByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPuzzleByIdResponse) GetGameState() []*GetPuzzleByIdResponse_PositionSchema {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetPuzzleByIdResponse) GetPlayerSide() string {
	if x != nil {
		return x.PlayerSide
	}
	return ""
}

func (x *GetPuzzleByIdResponse) GetMoves() []string {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *GetPuzzleByIdResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type CreatePuzzleRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	GameState     []*CreatePuzzleRequest_PositionSchema `protobuf:"bytes,1,rep,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	PlayerSide    string                                `protobuf:"bytes,2,opt,name=player_side,json=playerSide,proto3" json:"player_side,omitempty"`
	Moves         []string                              `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	Level         int32                                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePuzzleRequest) Reset() {
	*x = CreatePuzzleRequest{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePuzzleRequest) ProtoMessage() {}

func (x *CreatePuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePuzzleRequest.ProtoReflect.Descriptor instead.
func (*CreatePuzzleRequest) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePuzzleRequest) GetGameState() []*CreatePuzzleRequest_PositionSchema {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *CreatePuzzleRequest) GetPlayerSide() string {
	if x != nil {
		return x.PlayerSide
	}
	return ""
}

func (x *CreatePuzzleRequest) GetMoves() []string {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *CreatePuzzleRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type CreatePuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePuzzleResponse) Reset() {
	*x = CreatePuzzleResponse{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePuzzleResponse) ProtoMessage() {}

func (x *CreatePuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePuzzleResponse.ProtoReflect.Descriptor instead.
func (*CreatePuzzleResponse) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePuzzleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPuzzleResponse_PositionSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         string                 `protobuf:"bytes,1,opt,name=piece,proto3" json:"piece,omitempty"`
	Placement     string                 `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleResponse_PositionSchema) Reset() {
	*x = GetPuzzleResponse_PositionSchema{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleResponse_PositionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleResponse_PositionSchema) ProtoMessage() {}

func (x *GetPuzzleResponse_PositionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleResponse_PositionSchema.ProtoReflect.Descriptor instead.
func (*GetPuzzleResponse_PositionSchema) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetPuzzleResponse_PositionSchema) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

func (x *GetPuzzleResponse_PositionSchema) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

type GetPuzzleByIdResponse_PositionSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         string                 `protobuf:"bytes,1,opt,name=piece,proto3" json:"piece,omitempty"`
	Placement     string                 `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleByIdResponse_PositionSchema) Reset() {
	*x = GetPuzzleByIdResponse_PositionSchema{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleByIdResponse_PositionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleByIdResponse_PositionSchema) ProtoMessage() {}

func (x *GetPuzzleByIdResponse_PositionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleByIdResponse_PositionSchema.ProtoReflect.Descriptor instead.
func (*GetPuzzleByIdResponse_PositionSchema) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetPuzzleByIdResponse_PositionSchema) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

func (x *GetPuzzleByIdResponse_PositionSchema) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

type CreatePuzzleRequest_PositionSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         string                 `protobuf:"bytes,1,opt,name=piece,proto3" json:"piece,omitempty"`
	Placement     string                 `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePuzzleRequest_PositionSchema) Reset() {
	*x = CreatePuzzleRequest_PositionSchema{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePuzzleRequest_PositionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePuzzleRequest_PositionSchema) ProtoMessage() {}

func (x *CreatePuzzleRequest_PositionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePuzzleRequest_PositionSchema.ProtoReflect.Descriptor instead.
func (*CreatePuzzleRequest_PositionSchema) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreatePuzzleRequest_PositionSchema) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

func (x *CreatePuzzleRequest_PositionSchema) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

var File_puzzles_v1_puzzles_proto protoreflect.FileDescriptor

var file_puzzles_v1_puzzles_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x83, 0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4b, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x1a, 0x44, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8b,
	0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4f, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x76, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x1a, 0x44, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xf7, 0x01, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x1a, 0x44, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0xa5,
	0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x42, 0x0c, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75,
	0x63, 0x61, 0x73, 0x2d, 0x77, 0x6f, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2d, 0x63, 0x6c,
	0x6f, 0x6e, 0x65, 0x2d, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x0a, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x16, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x50, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_puzzles_v1_puzzles_proto_rawDescOnce sync.Once
	file_puzzles_v1_puzzles_proto_rawDescData []byte
)

func file_puzzles_v1_puzzles_proto_rawDescGZIP() []byte {
	file_puzzles_v1_puzzles_proto_rawDescOnce.Do(func() {
		file_puzzles_v1_puzzles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_puzzles_v1_puzzles_proto_rawDesc), len(file_puzzles_v1_puzzles_proto_rawDesc)))
	})
	return file_puzzles_v1_puzzles_proto_rawDescData
}

var file_puzzles_v1_puzzles_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_puzzles_v1_puzzles_proto_goTypes = []any{
	(*GetPuzzleRequest)(nil),                     // 0: puzzles.v1.GetPuzzleRequest
	(*GetPuzzleResponse)(nil),                    // 1: puzzles.v1.GetPuzzleResponse
	(*GetPuzzleByIdRequest)(nil),                 // 2: puzzles.v1.GetPuzzleByIdRequest
	(*GetPuzzleByIdResponse)(nil),                // 3: puzzles.v1.GetPuzzleByIdResponse
	(*CreatePuzzleRequest)(nil),                  // 4: puzzles.v1.CreatePuzzleRequest
	(*CreatePuzzleResponse)(nil),                 // 5: puzzles.v1.CreatePuzzleResponse
	(*GetPuzzleResponse_PositionSchema)(nil),     // 6: puzzles.v1.GetPuzzleResponse.PositionSchema
	(*GetPuzzleByIdResponse_PositionSchema)(nil), // 7: puzzles.v1.GetPuzzleByIdResponse.PositionSchema
	(*CreatePuzzleRequest_PositionSchema)(nil),   // 8: puzzles.v1.CreatePuzzleRequest.PositionSchema
}
var file_puzzles_v1_puzzles_proto_depIdxs = []int32{
	6, // 0: puzzles.v1.GetPuzzleResponse.game_state:type_name -> puzzles.v1.GetPuzzleResponse.PositionSchema
	7, // 1: puzzles.v1.GetPuzzleByIdResponse.game_state:type_name -> puzzles.v1.GetPuzzleByIdResponse.PositionSchema
	8, // 2: puzzles.v1.CreatePuzzleRequest.game_state:type_name -> puzzles.v1.CreatePuzzleRequest.PositionSchema
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_puzzles_v1_puzzles_proto_init() }
func file_puzzles_v1_puzzles_proto_init() {
	if File_puzzles_v1_puzzles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_puzzles_v1_puzzles_proto_rawDesc), len(file_puzzles_v1_puzzles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_puzzles_v1_puzzles_proto_goTypes,
		DependencyIndexes: file_puzzles_v1_puzzles_proto_depIdxs,
		MessageInfos:      file_puzzles_v1_puzzles_proto_msgTypes,
	}.Build()
	File_puzzles_v1_puzzles_proto = out.File
	file_puzzles_v1_puzzles_proto_goTypes = nil
	file_puzzles_v1_puzzles_proto_depIdxs = nil
}
