// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: puzzles/v1/puzzles.proto

package puzzles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPuzzleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleRequest) Reset() {
	*x = GetPuzzleRequest{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleRequest) ProtoMessage() {}

func (x *GetPuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleRequest.ProtoReflect.Descriptor instead.
func (*GetPuzzleRequest) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{0}
}

func (x *GetPuzzleRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type GetPuzzleResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	GameState     []*GetPuzzleResponse_PositionSchema `protobuf:"bytes,1,rep,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	PlayerSide    string                              `protobuf:"bytes,2,opt,name=player_side,json=playerSide,proto3" json:"player_side,omitempty"`
	Moves         []string                            `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	Level         int32                               `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleResponse) Reset() {
	*x = GetPuzzleResponse{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleResponse) ProtoMessage() {}

func (x *GetPuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleResponse.ProtoReflect.Descriptor instead.
func (*GetPuzzleResponse) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{1}
}

func (x *GetPuzzleResponse) GetGameState() []*GetPuzzleResponse_PositionSchema {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetPuzzleResponse) GetPlayerSide() string {
	if x != nil {
		return x.PlayerSide
	}
	return ""
}

func (x *GetPuzzleResponse) GetMoves() []string {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *GetPuzzleResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetPuzzleResponse_PositionSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piece         string                 `protobuf:"bytes,1,opt,name=piece,proto3" json:"piece,omitempty"`
	Placement     string                 `protobuf:"bytes,2,opt,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleResponse_PositionSchema) Reset() {
	*x = GetPuzzleResponse_PositionSchema{}
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleResponse_PositionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleResponse_PositionSchema) ProtoMessage() {}

func (x *GetPuzzleResponse_PositionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_puzzles_v1_puzzles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleResponse_PositionSchema.ProtoReflect.Descriptor instead.
func (*GetPuzzleResponse_PositionSchema) Descriptor() ([]byte, []int) {
	return file_puzzles_v1_puzzles_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetPuzzleResponse_PositionSchema) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

func (x *GetPuzzleResponse_PositionSchema) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

var File_puzzles_v1_puzzles_proto protoreflect.FileDescriptor

var file_puzzles_v1_puzzles_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0xf3, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x69,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x1a, 0x44, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0xa3, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x50, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x63, 0x61, 0x73, 0x2d, 0x77, 0x6f, 0x6f, 0x2f,
	0x63, 0x68, 0x65, 0x73, 0x73, 0x2d, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x2d, 0x76, 0x32, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x73, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x50, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x50, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0b, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_puzzles_v1_puzzles_proto_rawDescOnce sync.Once
	file_puzzles_v1_puzzles_proto_rawDescData []byte
)

func file_puzzles_v1_puzzles_proto_rawDescGZIP() []byte {
	file_puzzles_v1_puzzles_proto_rawDescOnce.Do(func() {
		file_puzzles_v1_puzzles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_puzzles_v1_puzzles_proto_rawDesc), len(file_puzzles_v1_puzzles_proto_rawDesc)))
	})
	return file_puzzles_v1_puzzles_proto_rawDescData
}

var file_puzzles_v1_puzzles_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_puzzles_v1_puzzles_proto_goTypes = []any{
	(*GetPuzzleRequest)(nil),                 // 0: puzzles.v1.GetPuzzleRequest
	(*GetPuzzleResponse)(nil),                // 1: puzzles.v1.GetPuzzleResponse
	(*GetPuzzleResponse_PositionSchema)(nil), // 2: puzzles.v1.GetPuzzleResponse.PositionSchema
}
var file_puzzles_v1_puzzles_proto_depIdxs = []int32{
	2, // 0: puzzles.v1.GetPuzzleResponse.game_state:type_name -> puzzles.v1.GetPuzzleResponse.PositionSchema
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_puzzles_v1_puzzles_proto_init() }
func file_puzzles_v1_puzzles_proto_init() {
	if File_puzzles_v1_puzzles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_puzzles_v1_puzzles_proto_rawDesc), len(file_puzzles_v1_puzzles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_puzzles_v1_puzzles_proto_goTypes,
		DependencyIndexes: file_puzzles_v1_puzzles_proto_depIdxs,
		MessageInfos:      file_puzzles_v1_puzzles_proto_msgTypes,
	}.Build()
	File_puzzles_v1_puzzles_proto = out.File
	file_puzzles_v1_puzzles_proto_goTypes = nil
	file_puzzles_v1_puzzles_proto_depIdxs = nil
}
