// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: puzzles/v1/service.proto

package puzzlesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PuzzlesService_GetPuzzle_FullMethodName     = "/puzzles.v1.PuzzlesService/GetPuzzle"
	PuzzlesService_CreatePuzzle_FullMethodName  = "/puzzles.v1.PuzzlesService/CreatePuzzle"
	PuzzlesService_GetPuzzleById_FullMethodName = "/puzzles.v1.PuzzlesService/GetPuzzleById"
)

// PuzzlesServiceClient is the client API for PuzzlesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PuzzlesServiceClient interface {
	GetPuzzle(ctx context.Context, in *GetPuzzleRequest, opts ...grpc.CallOption) (*GetPuzzleResponse, error)
	CreatePuzzle(ctx context.Context, in *CreatePuzzleRequest, opts ...grpc.CallOption) (*CreatePuzzleResponse, error)
	GetPuzzleById(ctx context.Context, in *GetPuzzleByIdRequest, opts ...grpc.CallOption) (*GetPuzzleByIdResponse, error)
}

type puzzlesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPuzzlesServiceClient(cc grpc.ClientConnInterface) PuzzlesServiceClient {
	return &puzzlesServiceClient{cc}
}

func (c *puzzlesServiceClient) GetPuzzle(ctx context.Context, in *GetPuzzleRequest, opts ...grpc.CallOption) (*GetPuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPuzzleResponse)
	err := c.cc.Invoke(ctx, PuzzlesService_GetPuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puzzlesServiceClient) CreatePuzzle(ctx context.Context, in *CreatePuzzleRequest, opts ...grpc.CallOption) (*CreatePuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePuzzleResponse)
	err := c.cc.Invoke(ctx, PuzzlesService_CreatePuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puzzlesServiceClient) GetPuzzleById(ctx context.Context, in *GetPuzzleByIdRequest, opts ...grpc.CallOption) (*GetPuzzleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPuzzleByIdResponse)
	err := c.cc.Invoke(ctx, PuzzlesService_GetPuzzleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PuzzlesServiceServer is the server API for PuzzlesService service.
// All implementations must embed UnimplementedPuzzlesServiceServer
// for forward compatibility.
type PuzzlesServiceServer interface {
	GetPuzzle(context.Context, *GetPuzzleRequest) (*GetPuzzleResponse, error)
	CreatePuzzle(context.Context, *CreatePuzzleRequest) (*CreatePuzzleResponse, error)
	GetPuzzleById(context.Context, *GetPuzzleByIdRequest) (*GetPuzzleByIdResponse, error)
	mustEmbedUnimplementedPuzzlesServiceServer()
}

// UnimplementedPuzzlesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPuzzlesServiceServer struct{}

func (UnimplementedPuzzlesServiceServer) GetPuzzle(context.Context, *GetPuzzleRequest) (*GetPuzzleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPuzzle not implemented")
}
func (UnimplementedPuzzlesServiceServer) CreatePuzzle(context.Context, *CreatePuzzleRequest) (*CreatePuzzleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePuzzle not implemented")
}
func (UnimplementedPuzzlesServiceServer) GetPuzzleById(context.Context, *GetPuzzleByIdRequest) (*GetPuzzleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPuzzleById not implemented")
}
func (UnimplementedPuzzlesServiceServer) mustEmbedUnimplementedPuzzlesServiceServer() {}
func (UnimplementedPuzzlesServiceServer) testEmbeddedByValue()                        {}

// UnsafePuzzlesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PuzzlesServiceServer will
// result in compilation errors.
type UnsafePuzzlesServiceServer interface {
	mustEmbedUnimplementedPuzzlesServiceServer()
}

func RegisterPuzzlesServiceServer(s grpc.ServiceRegistrar, srv PuzzlesServiceServer) {
	// If the following call pancis, it indicates UnimplementedPuzzlesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PuzzlesService_ServiceDesc, srv)
}

func _PuzzlesService_GetPuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzlesServiceServer).GetPuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzlesService_GetPuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzlesServiceServer).GetPuzzle(ctx, req.(*GetPuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuzzlesService_CreatePuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzlesServiceServer).CreatePuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzlesService_CreatePuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzlesServiceServer).CreatePuzzle(ctx, req.(*CreatePuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuzzlesService_GetPuzzleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPuzzleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzlesServiceServer).GetPuzzleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzlesService_GetPuzzleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzlesServiceServer).GetPuzzleById(ctx, req.(*GetPuzzleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PuzzlesService_ServiceDesc is the grpc.ServiceDesc for PuzzlesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PuzzlesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puzzles.v1.PuzzlesService",
	HandlerType: (*PuzzlesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPuzzle",
			Handler:    _PuzzlesService_GetPuzzle_Handler,
		},
		{
			MethodName: "CreatePuzzle",
			Handler:    _PuzzlesService_CreatePuzzle_Handler,
		},
		{
			MethodName: "GetPuzzleById",
			Handler:    _PuzzlesService_GetPuzzleById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "puzzles/v1/service.proto",
}
