syntax="proto3";

option go_package = "github.com/lucas-woo/chess-clone-v2/api/authentication/v1/authv1";

package authentication.v1;

message SignUpUserRequest {
  string username = 1;
  string hashed_password = 2;
  string email = 3;
  bool remember_me = 4;
}

message SignUpUserResponse {
  enum SignUpError {
    SIGN_UP_ERROR_UNSPECIFIED = 0;
    SIGN_UP_ERROR_INVALID_EMAIL = 1;
    SIGN_UP_ERROR_EMAIL_ALREADY_TAKEN = 2;
    SIGN_UP_ERROR_INVALID_USERNAME = 3;
    SIGN_UP_ERROR_USERNAME_ALREADY_TAKEN = 4;
    SIGN_UP_ERROR_INVALID_PASSWORD = 5;
  }
  SignUpError signup_error = 1;
  string session_id = 2;
}

message LoginUserRequest {
  string hashed_password = 1;
  string email = 2;  
  bool remember_me = 3;
}

message LoginUserResponse {
  enum LoginError {
    LOGIN_ERROR_UNSPECIFIED = 0;
    LOGIN_ERROR_INVALID_CREDENTIALS = 1;
  }
  LoginError login_error = 1;
  string session_id = 2;
}

message LogoutUserRequest {
  string session_id = 1;
}

message LogoutUserResponse {
  bool logged_out = 1;
}

message VerifyUsernameRequest {
  string username = 1;
}

message VerifyUsernameResponse {
  bool username_taken = 1;
}